let employees=[
{"eid":1,"ename":"Kata","gender":"Female","country":"Indonesia"},
{"eid":2,"ename":"Angelita","gender":"Female","country":"Indonesia"},
{"eid":3,"ename":"Terza","gender":"Female","country":"Indonesia"},
{"eid":4,"ename":"Eloisa","gender":"Female","country":"Ukraine"},
{"eid":5,"ename":"Sophie","gender":"Female","country":"China"},
{"eid":6,"ename":"Muire","gender":"Female","country":"Nicaragua"},
{"eid":7,"ename":"Brant","gender":"Male","country":"Indonesia"},
{"eid":8,"ename":"Robers","gender":"Male","country":"Japan"},
{"eid":9,"ename":"Philippa","gender":"Agender","country":"Indonesia"},
{"eid":10,"ename":"Torey","gender":"Female","country":"Philippines"},
{"eid":11,"ename":"Johny","gender":"Male","country":"Serbia"},
{"eid":12,"ename":"Casar","gender":"Male","country":"Indonesia"},
{"eid":13,"ename":"Trista","gender":"Female","country":"Turkmenistan"},
{"eid":14,"ename":"Beverley","gender":"Female","country":"China"},
{"eid":15,"ename":"Letty","gender":"Female","country":"Brazil"},
{"eid":16,"ename":"Shawn","gender":"Male","country":"Peru"},
{"eid":17,"ename":"Tallia","gender":"Female","country":"Nigeria"},
{"eid":18,"ename":"Talyah","gender":"Agender","country":"Russia"},
{"eid":19,"ename":"Rubia","gender":"Female","country":"Indonesia"},
{"eid":20,"ename":"Trescha","gender":"Female","country":"Poland"},
{"eid":21,"ename":"Timothy","gender":"Male","country":"China"},
{"eid":22,"ename":"Sharline","gender":"Female","country":"Colombia"},
{"eid":23,"ename":"Shaina","gender":"Female","country":"China"},
{"eid":24,"ename":"Maurise","gender":"Female","country":"China"},
{"eid":25,"ename":"Glad","gender":"Female","country":"Portugal"},
{"eid":26,"ename":"Johannah","gender":"Female","country":"Venezuela"},
{"eid":27,"ename":"Eleni","gender":"Female","country":"France"},
{"eid":28,"ename":"North","gender":"Polygender","country":"Iceland"},
{"eid":29,"ename":"Enrika","gender":"Female","country":"Ukraine"},
{"eid":30,"ename":"Jasmine","gender":"Female","country":"Indonesia"},
{"eid":31,"ename":"Vally","gender":"Female","country":"Indonesia"},
{"eid":32,"ename":"Norrie","gender":"Female","country":"China"},
{"eid":33,"ename":"Linnea","gender":"Female","country":"Indonesia"},
{"eid":34,"ename":"Sara-ann","gender":"Female","country":"China"},
{"eid":35,"ename":"Meghann","gender":"Female","country":"Indonesia"},
{"eid":36,"ename":"Ailyn","gender":"Female","country":"Venezuela"},
{"eid":37,"ename":"Dee","gender":"Female","country":"Russia"},
{"eid":38,"ename":"Pen","gender":"Female","country":"Indonesia"},
{"eid":39,"ename":"Lazar","gender":"Male","country":"Sweden"},
{"eid":40,"ename":"Edeline","gender":"Female","country":"China"},
{"eid":41,"ename":"Annabell","gender":"Agender","country":"Mongolia"},
{"eid":42,"ename":"Hyacinth","gender":"Female","country":"Iran"},
{"eid":43,"ename":"Tris","gender":"Male","country":"Portugal"},
{"eid":44,"ename":"Errol","gender":"Male","country":"China"},
{"eid":45,"ename":"Greggory","gender":"Male","country":"Philippines"},
{"eid":46,"ename":"Edd","gender":"Male","country":"Russia"},
{"eid":47,"ename":"Raddy","gender":"Male","country":"Indonesia"},
{"eid":48,"ename":"Whitman","gender":"Male","country":"United States"},
{"eid":49,"ename":"Tove","gender":"Female","country":"Democratic Republic of the Congo"},
{"eid":50,"ename":"Kari","gender":"Agender","country":"Nigeria"},
{"eid":51,"ename":"Maurizio","gender":"Male","country":"Indonesia"},
{"eid":52,"ename":"Laural","gender":"Female","country":"China"},
{"eid":53,"ename":"Raquel","gender":"Female","country":"Sweden"},
{"eid":54,"ename":"Lolita","gender":"Female","country":"Nigeria"},
{"eid":55,"ename":"Ryun","gender":"Polygender","country":"Bosnia and Herzegovina"},
{"eid":56,"ename":"Nealon","gender":"Male","country":"Pakistan"},
{"eid":57,"ename":"Rowena","gender":"Female","country":"Bulgaria"},
{"eid":58,"ename":"Margaretta","gender":"Female","country":"Colombia"},
{"eid":59,"ename":"Pasquale","gender":"Male","country":"Brazil"},
{"eid":60,"ename":"Loni","gender":"Female","country":"Philippines"},
{"eid":61,"ename":"Sigfrid","gender":"Male","country":"Czech Republic"},
{"eid":62,"ename":"Merwyn","gender":"Bigender","country":"Russia"},
{"eid":63,"ename":"Hurley","gender":"Male","country":"China"},
{"eid":64,"ename":"Krista","gender":"Female","country":"Ukraine"},
{"eid":65,"ename":"Ryan","gender":"Male","country":"France"},
{"eid":66,"ename":"Way","gender":"Male","country":"China"},
{"eid":67,"ename":"Pammi","gender":"Female","country":"France"},
{"eid":68,"ename":"Malvin","gender":"Male","country":"Russia"},
{"eid":69,"ename":"Courtnay","gender":"Male","country":"Indonesia"},
{"eid":70,"ename":"Kalindi","gender":"Female","country":"Peru"},
{"eid":71,"ename":"Wit","gender":"Male","country":"China"},
{"eid":72,"ename":"Normy","gender":"Male","country":"China"},
{"eid":73,"ename":"Adolph","gender":"Polygender","country":"China"},
{"eid":74,"ename":"Milo","gender":"Male","country":"Chile"},
{"eid":75,"ename":"Byram","gender":"Male","country":"France"},
{"eid":76,"ename":"Jefferey","gender":"Male","country":"Peru"},
{"eid":77,"ename":"Verine","gender":"Female","country":"Germany"},
{"eid":78,"ename":"Enrique","gender":"Non-binary","country":"Portugal"},
{"eid":79,"ename":"Ado","gender":"Non-binary","country":"China"},
{"eid":80,"ename":"Vikky","gender":"Female","country":"Belarus"},
{"eid":81,"ename":"Marleah","gender":"Female","country":"Ukraine"},
{"eid":82,"ename":"Cobby","gender":"Male","country":"China"},
{"eid":83,"ename":"Rriocard","gender":"Male","country":"Nicaragua"},
{"eid":84,"ename":"Brit","gender":"Female","country":"Philippines"},
{"eid":85,"ename":"Melli","gender":"Female","country":"China"},
{"eid":86,"ename":"Burke","gender":"Male","country":"Poland"},
{"eid":87,"ename":"Simeon","gender":"Male","country":"Belarus"},
{"eid":88,"ename":"Kakalina","gender":"Female","country":"Ukraine"},
{"eid":89,"ename":"Roma","gender":"Male","country":"China"},
{"eid":90,"ename":"Dulcia","gender":"Female","country":"Indonesia"},
{"eid":91,"ename":"Von","gender":"Male","country":"Indonesia"},
{"eid":92,"ename":"Kellen","gender":"Female","country":"Myanmar"},
{"eid":93,"ename":"Ephrem","gender":"Male","country":"Botswana"},
{"eid":94,"ename":"Sheba","gender":"Female","country":"China"},
{"eid":95,"ename":"Adelaide","gender":"Bigender","country":"Indonesia"},
{"eid":96,"ename":"Shaine","gender":"Male","country":"Russia"},
{"eid":97,"ename":"Tanny","gender":"Male","country":"Portugal"},
{"eid":98,"ename":"Adelaida","gender":"Genderfluid","country":"Russia"},
{"eid":99,"ename":"Elfrida","gender":"Female","country":"Russia"},
{"eid":100,"ename":"Kahlil","gender":"Male","country":"France"}]
console.log(employees.length)
//print no of female chaina employees
//print no of Male India employees
let femae_count=0
for(let emp of employees){
    if(emp.gender ==="Female" && emp.country==="China"){
        femae_count++;
    }
}
console.log("No of female Employees:",femae_count)